### ISSUE TITLE
WorkAround on OAuth authenticated scripts

### ISSUE THREAD

**Issue by CurlyBytes** [eL-Prova/owasp-zap-scripts#1]
Hi sir @eL-Prova , thank you for your time, if you just knew how much trouble am I, and I'm very grateful for your kind response in the [issue thread ere](https://github.com/kasunkv/owasp-zap-vsts-task/issues/53)

* Open Owasp Zap 2.7.0
* Plugins are default one installed
* Add script under **Authentication**  (i did modification because im using Azure Active Directory and add more _print_ function)

```
var HttpRequestHeader = Java.type("org.parosproxy.paros.network.HttpRequestHeader");
var HttpHeader = Java.type("org.parosproxy.paros.network.HttpHeader");
var URI = Java.type("org.apache.commons.httpclient.URI");

function authenticate(helper, paramsValues, credentials) {
	print("Authenticating via JavaScript script as client secret…");
 	var authHelper = new OAuthAuthenticator(helper, paramsValues, credentials);
	return authHelper.login();
}

function getRequiredParamsNames(){
	return ["tenant_id","client_id","client_secret","scope"];
}

function getOptionalParamsNames(){
	return [];
}

function getCredentialsParamsNames(){
	return ["username", "password"];
}

function OAuthAuthenticator(helper, paramsValues, credentials) {
	this.helper = helper;
	this.tenant_id = paramsValues.get('tenant_id');
	this.client_id = paramsValues.get('client_id');
	this.client_secret = paramsValues.get('client_secret');
	this.scope = paramsValues.get('scope');
	return this;
}

OAuthAuthenticator.prototype = {
	login: function () {
		print("Starting with authenticat..");
 		var loginToken,
		requestBody = 'grant_type=' + encodeURIComponent('client_credentials') +
                '&client_id=' + encodeURIComponent(this.client_id) +
                '&client_secret=' + encodeURIComponent(this.client_secret) +
			    '&scope=' + encodeURIComponent(this.scope),
 		response = this.doRequest("https://login.microsoftonline.com/" + encodeURIComponent(this.tenant_id) + "/oauth2/v2.0/token", HttpRequestHeader.POST, requestBody);

		if(response.getResponseHeader().isJson()) {
			var parsedResponse = JSON.parse(response.getResponseBody().toString());
		
			if (parsedResponse.error != null) {
				print('Authentication failure:');
				print(parsedResponse.error_description);
			} else {
				print("Token found, save as variable.");
				print("Token:" + parsedResponse.access_token);
				org.zaproxy.zap.extension.script.ScriptVars.setGlobalVar("access_token",parsedResponse.access_token);
			}
		} else {
			print('Wrong setup of request because no JSON is returned!');
		}
		return response;
 	},
	doRequest: function (url, requestMethod, requestBody) {
		var msg,
			requestUri = new URI(url, false);
            
		requestHeader = new HttpRequestHeader(requestMethod, requestUri, HttpHeader.HTTP10);

		msg = this.helper.prepareMessage();
		msg.setRequestHeader(requestHeader);
		msg.setRequestBody(requestBody);
		
		requestHeader.setContentLength(requestBody.length);

		this.helper.sendAndReceive(msg);

		return msg;
	}
};
```

* Add script under **HttpSender** (I did slight changes for debugging purposes)

```
function sendingRequest(msg, initiator, helper) {
    var access_token = org.zaproxy.zap.extension.script.ScriptVars.getGlobalVar("access_token");
   

            //set http header
            var httpRequestHeader = msg.getRequestHeader();
            httpRequestHeader.setHeader("Authorization","Bearer "+access_token);
            msg.setRequestHeader(httpRequestHeader);
            print('Requesting with Bearer Token of ' + access_token);

}

function responseReceived(msg, initiator, helper) {
  print('Request called for url=' + msg.getRequestHeader().getURI().toString());
  print('----------------------');
  print('----------------------');   
}
```

* did make sure the Http sender script is enabled and check
* goto the **Contexts** and modify the _Default Context_\
* Add the desired URL with wild cards 
* Navigate on Contexts node tree and go to Authentication, select **script-based authentication** and load the custom script that we define in the **Authentication** ScriptVars
* provide the CLient Id, CLient secret, tenant id and scope (leave blank the login and logout regex)
* still on Contexts tab and navigate to **Users** and add Guest (username and password are all values as _guest_) and ensure this account is enabled
* still on contexts tab and navigate to **Session Management**, in the dropdown  choose **Http Authentication Session Management**
*  double check and click the **Ok** button to ensure it is saved
* check the Option in tab by enabling "ForceUserMode"
* invoke new spider scan with COntext being defined (see attached picture) and user dropdown and the user account defined in the context(just one only)
![Step1](https://user-images.githubusercontent.com/55616292/93893375-23d27f80-fd20-11ea-8df1-9c861481cee5.JPG)

* after the spider scan(see next screenshot) there is now the SSO return URL from Azure Active Directory, with that URL I did include it as in the context
![image](https://user-images.githubusercontent.com/55616292/93894250-1964b580-fd21-11ea-9d28-0b982472c16b.png)

* and from that scan, the Authentication is really successfully its because it has now return token (see next image)
![Step3](https://user-images.githubusercontent.com/55616292/93893421-3056d800-fd20-11ea-95c5-47c0633dca9d.JPG)

* but the twist it just returns the result to 302 which indicates there is redirection and the scanning is not completed it was because it is not followed(this is now my assumption and see the image and all results either 302 and 404) therefore the actual scanning inside the application is not working 
![Step4](https://user-images.githubusercontent.com/55616292/93893432-3351c880-fd20-11ea-81e0-fd10073a5867.JPG)

* But i did one manual action to make a change, i did include the authentication url from the azure active directory (the left side from login.microsoftonline.com) add the wild card in the Context that created. Then perform spider scan and Active scan and now we have combination result 200, 302, and 404 (see image below)
![Step5](https://user-images.githubusercontent.com/55616292/93893457-3c429a00-fd20-11ea-95a0-0be7631f2f3a.JPG)

Possible Resolution to work the script much better, update the HttpSender script that scans properly with the manual steps define above
![Step6](https://user-images.githubusercontent.com/55616292/93893468-3e0c5d80-fd20-11ea-86c4-7fb2978d2925.JPG)

P.S. = Im sure that client id, client secret, tenant id and scope are the correct ones, both tested on postman and manual login via a web browser to an application

**Comment by eL-Prova** [comment]
If I am correct, your steps are good written and similar like how got it work.
I will close the issue, if you expect that I do something extra, let me know.

**Comment by CurlyBytes** [comment]
@eL-Prova  yes this is the something extra could help the organization a lot

> but the twist it just returns the result to 302 which indicates there is redirection and the scanning is not completed it was because it is not followed(this is now my assumption and see the image and all results either 302 and 404) therefore the actual scanning inside the application is not working

HTTP sender should execute it properly without any manual intervention in the GUI to active scan
